jobs:
  deploy:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install git -y

      - name: Build and deploy
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git subtree push --prefix build/www origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PAT }}
